FROM php:5.6-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y git 
RUN apt-get update && apt-get install -y curl
RUN apt-get update && apt-get install -y cron
RUN apt-get update && apt-get install -y libpng-dev
RUN apt-get update && apt-get install -y libonig-dev
RUN apt-get update && apt-get install -y libxml2-dev
RUN apt-get update && apt-get install -y libfreetype6-dev
RUN apt-get update && apt-get install -y libicu-dev
RUN apt-get update && apt-get install -y libjpeg62-turbo-dev 
RUN apt-get update && apt-get install -y libmcrypt-dev
RUN apt-get update && apt-get install -y libxslt1-dev
RUN apt-get update && apt-get install -y libxslt-dev
RUN apt-get update && apt-get install -y libzip-dev
RUN apt-get update && apt-get install -y libbz2-dev
RUN apt-get update && apt-get install -y zip
RUN apt-get update && apt-get install -y freetds-bin
RUN apt-get update && apt-get install -y freetds-common
RUN apt-get update && apt-get install -y freetds-dev
RUN apt-get update && apt-get install -y libct4
RUN apt-get update && apt-get install -y libsybdb5
RUN apt-get update && apt-get install -y tdsodbc
RUN apt-get update && apt-get install -y libldap2-dev
RUN apt-get update && apt-get install -y zlib1g-dev
RUN apt-get update && apt-get install -y libc-client-dev
RUN apt-get update && apt-get install -y libsqlite3-dev
RUN apt-get update && apt-get install -y libpq-dev
RUN apt-get update && apt-get install -y unzip

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

RUN ln -s /usr/lib/x86_64-linux-gnu/libsybdb.so /usr/lib/

# Install PHP extensions
RUN docker-php-ext-install bz2
RUN docker-php-ext-install bcmath
RUN docker-php-ext-install ctype
RUN docker-php-ext-install fileinfo
RUN docker-php-ext-install json
RUN docker-php-ext-install mbstring
RUN docker-php-ext-install exif
RUN docker-php-ext-install pcntl
RUN docker-php-ext-install gd
RUN docker-php-ext-install intl
RUN docker-php-ext-install mysql
RUN docker-php-ext-install mysqli
# RUN docker-php-ext-install mysqlnd
RUN docker-php-ext-install pdo
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install pdo_pgsql
RUN docker-php-ext-install pdo_sqlite
RUN docker-php-ext-install pdo_dblib
RUN docker-php-ext-install pgsql
RUN docker-php-ext-install session
RUN docker-php-ext-install soap
# RUN docker-php-ext-install sqlite3
RUN docker-php-ext-install tokenizer
RUN docker-php-ext-install wddx
RUN docker-php-ext-install xml
RUN docker-php-ext-install xmlreader
RUN docker-php-ext-install xmlrpc
RUN docker-php-ext-install xmlwriter
RUN docker-php-ext-install xsl
RUN docker-php-ext-install zip
# RUN docker-php-ext-install zlib

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"