name: Docker Check Build Image 

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Check Docker Files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            dockerfiles/**

      - name: Build the Docker image
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            docker build --file $file .
          done