name: Docker Build Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34

      - name: Build the Docker image
        # run: echo ${{ steps.changed-files.outputs.all_changed_files }}
        run: docker build --file ${{ steps.changed-files.outputs.all_changed_files }} -t test .
        # run: |
        #   for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
        #     image="$file"
        #     echo $image
        #     docker build --file $image -t test .
        #   done